### ISSUE TITLE
Upgrade ZFS to 2.2.0 for Mac

### ISSUE THREAD

**Issue by derritter88** [openzfsonosx/openzfs#123]
### Describe the feature would like to see added to OpenZFS
As ZFS 2.2.0 release I would love to see a release for Mac

### How will this feature improve OpenZFS?
Being able to use new ZFS on Mac

### Additional context
n/a

**Comment by derritter88** [comment]
@rottegift As this is marked completed and the ticket is closed, can you please let me know where to download the new version?

**Comment by lundman** [comment]
The plan was to wait for upstream merge, then release - but that seems a fool's errand. I will roll out a release shortly.

**Comment by derritter88** [comment]
@lundman Thanks Jorgen-san!
