### ISSUE TITLE
zdb does not translate xnu inode values to zfs

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/openzfs#53]
This causes `zdb -dddddd $ds $objnum` to fail for the "large" xnu inode values (16 reserved).

https://github.com/openzfsonosx/openzfs/blob/macOS_pure/tests/zfs-tests/include/blkdev.shlib#L609

@lundman suggests trying
```
if (rc == 0) {
    zor->zor_obj_start = INO_XNUTOZFS(zor->zor_obj_start, 2);
    zor->zor_obj_end = INO_XNUTOZFS(zor->zor_obj_end, 2);
```

(Issue discovered while fixing [tests/functional/checksum] test failures)

**Comment by lundman** [comment]
Test:  https://github.com/openzfsonosx/openzfs/pull/54
