### ISSUE TITLE
Panic while working with long paths

### ISSUE THREAD

**Issue by anongit** [openzfsonosx/openzfs#79]
Don't know if it's related to openzfsonosx/zfs#300 or #16, but it doesn't have multibyte filenames or filenames longer than 255.

<details>
<summary><b>Panic logs</b></summary>
<pre>
panic(cpu 0 caller 0xffffff800c003dbd): "__memmove_chk object size check failed: dst 0xffffff92910bb6f0, src 0xffffff802f408000, (256 < 261)"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.28.1/osfmk/device/subrs.c:701
Backtrace (CPU 0), Frame : Return Address
0xffffff92910bb3a0 : 0xffffff800bf1763d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff92910bb3f0 : 0xffffff800c051b25 mach_kernel : _kdp_i386_trap + 0x155
0xffffff92910bb430 : 0xffffff800c0436ae mach_kernel : _kernel_trap + 0x4ee
0xffffff92910bb480 : 0xffffff800bebda40 mach_kernel : _return_from_trap + 0xe0
0xffffff92910bb4a0 : 0xffffff800bf16d07 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff92910bb5a0 : 0xffffff800bf170f7 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff92910bb5f0 : 0xffffff800c6be82c mach_kernel : _panic + 0x54
0xffffff92910bb660 : 0xffffff800c003dbd mach_kernel : ___memmove_chk + 0x3d
0xffffff92910bb680 : 0xffffff7f8ccc9c2e org.openzfsonosx.zfs : _zfs_vnop_lookup + 0x6e
0xffffff92910bb820 : 0xffffff800c16bd0e mach_kernel : _lookup + 0x3ee
0xffffff92910bb980 : 0xffffff800c16aff1 mach_kernel : _namei + 0xdc1
0xffffff92910bbb80 : 0xffffff800c1848e5 mach_kernel : _nameiat + 0x75
0xffffff92910bbbd0 : 0xffffff800c18ab87 mach_kernel : _stat_extended + 0x187
0xffffff92910bbf10 : 0xffffff800c18b5af mach_kernel : _lstat64 + 0x2f
0xffffff92910bbf40 : 0xffffff800c5819a7 mach_kernel : _unix_syscall64 + 0x287
0xffffff92910bbfa0 : 0xffffff800bebe206 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         org.openzfsonosx.zfs(2.0.1)[C8900DAA-9C3B-36DD-8C6D-7869FC2DBF69]@0xffffff7f8cbb0000-0xffffff7f8e361fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[F3D120E5-29D0-32C7-A09A-E88B84675F9C]@0xffffff7f8cb10000
</pre>

Another one, don't know why this one is different, I might've hit an edge case for character length.

<pre>
panic(cpu 0 caller 0xffffff80234be782): "Kernel stack memory corruption detected"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.28.1/libkern/stack_protector.c:37
Backtrace (CPU 0), Frame : Return Address
0xffffff92257033a0 : 0xffffff8022d1763d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff92257033f0 : 0xffffff8022e51b25 mach_kernel : _kdp_i386_trap + 0x155
0xffffff9225703430 : 0xffffff8022e436ae mach_kernel : _kernel_trap + 0x4ee
0xffffff9225703480 : 0xffffff8022cbda40 mach_kernel : _return_from_trap + 0xe0
0xffffff92257034a0 : 0xffffff8022d16d07 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff92257035a0 : 0xffffff8022d170f7 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff92257035f0 : 0xffffff80234be82c mach_kernel : _panic + 0x54
0xffffff9225703660 : 0xffffff80234be782 mach_kernel : _mac_exc_action_check_exception_send + 0x3a2
0xffffff9225703670 : 0xffffff8022cda8e9 mach_kernel : ___stack_chk_fail + 0x9
0xffffff9225703680 : 0xffffff7fa3ac9f95 org.openzfsonosx.zfs : _zfs_vnop_lookup + 0x3d5
0xffffff9225703820 : 0xffffff8022f6bd0e mach_kernel : _lookup + 0x3ee
0xffffff9225703980 : 0xffffff8022f6aff1 mach_kernel : _namei + 0xdc1
0xffffff9225703b80 : 0xffffff8022f848e5 mach_kernel : _nameiat + 0x75
0xffffff9225703bd0 : 0xffffff8022f8ab87 mach_kernel : _stat_extended + 0x187
0xffffff9225703f10 : 0xffffff8022f8b5af mach_kernel : _lstat64 + 0x2f
0xffffff9225703f40 : 0xffffff80233819a7 mach_kernel : _unix_syscall64 + 0x287
0xffffff9225703fa0 : 0xffffff8022cbe206 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         org.openzfsonosx.zfs(2.0.1)[C8900DAA-9C3B-36DD-8C6D-7869FC2DBF69]@0xffffff7fa39b0000->0xffffff7fa5161fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[F3D120E5-29D0-32C7-A09A-E88B84675F9C]@0xffffff7fa3910000
</pre>

</details>

#### Steps to reproduce:

```shell
# Unfortunately I don't know what mc does exactly, 
# I couldn't reproduce with standard utils like ls / stat
brew install midnight-commander

truncate -s 100M /tmp/ztest.img
sudo zpool create ztest /tmp/ztest.img
sudo chown $(whoami) /Volumes/ztest/

# the path needs to be long, remove 6-7 chars and everything's okay
# notice that it's many nested directories, not a single one in /Volumes/ztest/
mkdir -p /Volumes/ztest/123456789.123456789/123456789.123456789.123456789/123456789.123456789.123456789/123456789.123456789/123456789.12345689.123456789/123456789.123456789.123456789/
cd /Volumes/ztest/123456789.123456789/123456789.123456789.123456789/123456789.123456789.123456789/123456789.123456789/123456789.12345689.123456789/123456789.123456789.123456789/
mc
# go to the parent directory and back
# panic here
```
#### System info:
```
zfs-macOS-2.0.1-1
zfs-kmod-2.0.1-1

macOS 10.15.7 (19H1030)
Darwin mars.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64 i386 Macmini6,2 Darwin
```

**Comment by lundman** [comment]
Yep, both of those apply and we believe it has been fixed. Please try 2.1.x when we release it, or from sources if you can.

**Comment by anongit** [comment]
Thanks, will do when it's released.
