### ISSUE TITLE
Regression: man pages not in folder recognised by terminal

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/openzfs#83]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Big Sur
Distribution Version	| 11.4
Linux Kernel	|
Architecture	|
ZFS Version	| 2.1 rc1
SPL Version	| ?

### Describe the problem you're observing

For all other commands not from zfs, the man pages are in a place where terminal.app finds them when entering rthe name (eg enter `grep` into the help search box.
### Describe how to reproduce the problem
Enter `zfs` or `zpool` in the help menu's search box

**Comment by JMoVS** [comment]
this was working on 1.9x series

**Comment by ilovezfs** [comment]
Odd, since `manpath` knows about them.

**Comment by JMoVS** [comment]
yep - typing `man zpool` works but that search box doesn't see it

**Comment by JMoVS** [comment]
seems to be a `terminal.app` bug
